repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
        exclude: 'charts/.*/templates/.*' # template files are not truly YAML
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.3
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: lint-all-helm-charts
        name: Lint all Helm charts
        entry: scripts/lint_all_helm_charts.sh
        language: script
        always_run: true
        pass_filenames: false
