apiVersion: v1
kind: Service
metadata:
  name: {{ include "wizard.fullname" . }}
  labels:
    {{- include "wizard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 8000
    targetPort: http
  - name: grpc
    port: 8001
    targetPort: grpc
  - name: metrics
    port: 8002
    targetPort: metrics
  selector:
    {{- include "wizard.selectorLabels" . | nindent 4 }}
