{{- $root := . -}}
{{- range .Values.runnerDeployments }}
{{- if $root.Values.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .name }}
  labels:
    {{- include "runners.labels" $ | nindent 4 }}
spec:
  behavior:
    scaleUp:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Max
      stabilizationWindowSeconds: 200
    scaleDown:
      policies:
        - type: Percent
          value: 20
          periodSeconds: 60
      selectPolicy: Max
      stabilizationWindowSeconds: 600
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .name }}
  minReplicas: {{ $root.Values.autoscaling.minReplicas }}
  maxReplicas: {{ $root.Values.autoscaling.maxReplicas }}
  metrics:
    - type: Object
      object:
        metric:
          name: {{ .hpa_metric_name }}
        describedObject:
          apiVersion: v1
          kind: Service
          name: rabbitmq-cluster
        target:
          type: Value
          value: {{ .concurrency }}
{{- end }}
{{- end }}
