apiVersion: v2
name: galileo
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.8.0

dependencies:
  - name: api
    version: "0.6.0"
    repository: "file://../api"
  - name: comet
    version: "0.3.0"
    repository: "file://../comet"
  - name: wizard
    version: "0.4.0"
    repository: "file://../wizard"
    condition: wizard.enabled
  - name: runners
    version: "0.5.0"
    repository: "file://../runners"
  - name: ui
    version: "0.5.0"
    repository: "file://../ui"
  - name: cert-manager
    version: "1.13.3"
    repository: "https://charts.jetstack.io"
    condition: cert-manager.enabled
  - name: minio
    version: "5.0.15"
    repository: "https://charts.min.io/"
    condition: minio.enabled
  - name: cloudnative-pg
    version: "0.20.0"
    repository: "https://cloudnative-pg.github.io/charts"
    condition: cloudnative-pg.enabled
  - name: rabbitmq-cluster-operator
    version: "3.15.4"
    repository: "https://charts.bitnami.com/bitnami"
  - name: clickhouse
    version: "6.2.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: clickhouse.enabled
  - name: metrics-server
    version: "3.12.1"
    repository: "https://kubernetes-sigs.github.io/metrics-server/"
    condition: metrics-server.enabled
  - name: prometheus
    version: "25.21.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: prometheus-operator-crds
    version: "12.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: prometheus-adapter
    version: "4.10.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus-adapter.enabled
