apiVersion: v2
name: galileo
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: api
    version: "0.1.0"
    repository: "file://../api"
  - name: comet
    version: "0.1.0"
    repository: "file://../comet"
  - name: model-server
    version: "0.1.0"
    repository: "file://../model-server"
  - name: runners
    version: "0.1.0"
    repository: "file://../runners"
  - name: ui
    version: "0.1.0"
    repository: "file://../ui"
  - name: cert-manager
    version: "1.13.3"
    repository: "https://charts.jetstack.io"
  - name: minio
    version: "5.0.15"
    repository: "https://charts.min.io/"
  - name: cloudnative-pg
    version: "0.20.0"
    repository: "https://cloudnative-pg.github.io/charts"
  - name: rabbitmq-cluster-operator
    version: "3.15.4"
    repository: "https://charts.bitnami.com/bitnami"
