nameOverride: ""
fullnameOverride: ""

# Cert-Manager configuration: https://artifacthub.io/packages/helm/cert-manager/cert-manager?modal=values
cert-manager:
  enabled: false
  fullnameOverride: "cert-manager"
  installCRDs: true

# Comet configuration
comet:
  nodeSelector: {}
  fullnameOverride: "comet"

# API configuration
api:
  nodeSelector: {}
  fullnameOverride: "api"
  env:
    GALILEO_CONSOLE_URL: "https://console.example.local"
    GALILEO_ADDITIONAL_ORIGINS: "*"
    GALILEO_HEADLESS_API_SVC_DNS: "api-hs.galileo.svc.cluster.local"
    GALILEO_RUNNERS_SVC_NAME: "runners-hs.galileo.svc.cluster.local"
    GALILEO_RUNNERS_SVC_PORT: "50052"
  ingress:
    enabled: true
    hosts:
      - host: api.example.local
        paths:
          - path: /
            pathType: Prefix

# Runners configuration
runners:
  nodeSelector: {}

# Wizard configuration
wizard:
  enabled: true
  nodeSelector: {}
  fullnameOverride: "wizard"

# UI configuration
ui:
  nodeSelector: {}
  fullnameOverride: "ui"
  env:
    NEXT_PUBLIC_API_URL: "http://api.example.local"
    NEXTAUTH_URL: "http://console.example.local"
  ingress:
    enabled: true
    hosts:
      - host: console.example.local
        paths:
          - path: /
            pathType: Prefix

# CloudNative PG configuration: https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/values.yaml
cloudnative-pg:
  enabled: true
  fullnameOverride: "cloudnative-pg"

# MinIO configuration: https://github.com/minio/minio/blob/master/helm/minio/values.yaml
minio:
  enabled: true
  fullnameOverride: "minio"
  replicas: 2 # 2 is the minimum
  existingSecret: minio-secret # specify user + password manually to avoid redeployments
  resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 1Gi
  buckets:
    - name: galileo-auto-datasets
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-images
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-models
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-project-runs
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-project-runs-results
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-prompts-datasets
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-prompts-results
      policy: none
      purge: false
      versioning: false
      objectlocking: false
  makePolicyJob:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  makeBucketJob:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  makeUserJob:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  customCommandJob:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  makeServiceAccountJob:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi


# RabbitMQ Operator configuration: https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq-cluster-operator/values.yaml
rabbitmq-cluster-operator:
  resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
  fullnameOverride: "rabbitmq-cluster-operator"
  msgTopologyOperator:
    fullnameOverride: "rabbitmq-messaging-topology-operator"
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi

# Clickhouse configuration: https://github.com/bitnami/charts/blob/main/bitnami/clickhouse/values.yaml
clickhouse:
  enabled: true
  fullnameOverride: "clickhouse"
  zookeeper:
    fullnameOverride: "zookeeper"

# Prometheus configuration: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
prometheus:
  enabled: true
  replicaCount: 2
  serviceAccount:
    create: false
    name: galileo
  alertmanager:
    enabled: true
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'kubernetes-pods'
        scrape_interval: 2m
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
    remoteWrite:
      - url: https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push
        basic_auth:
          username: ""
          password: ""
        write_relabel_configs:
          - source_labels: [__name__]
            regex: '^(api_|galileo_|job_|rabbitmq_queue_|nv_inference_|nv_gpu_|nv_cpu_).*'
            action: keep
          - source_labels: [queue]
            regex: '^(health|fast|normal|slow|$)'
            action: keep
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
  kubeStateMetrics:
    enabled: true
