nameOverride: ""
fullnameOverride: ""

# Cert-Manager configuration: https://artifacthub.io/packages/helm/cert-manager/cert-manager?modal=values
cert-manager:
  enabled: false
  fullnameOverride: "cert-manager"
  installCRDs: true

# Comet configuration
comet:
  nodeSelector: {}
  fullnameOverride: "comet"

# API configuration
api:
  nodeSelector: {}
  fullnameOverride: "api"
  env:
    GALILEO_CONSOLE_URL: "https://console.example.local"
    GALILEO_ADDITIONAL_ORIGINS: "*"
    GALILEO_HEADLESS_API_SVC_DNS: "api-hs.galileo.svc.cluster.local"
    GALILEO_RUNNERS_SVC_NAME: "runners-hs.galileo.svc.cluster.local"
    GALILEO_RUNNERS_SVC_PORT: "50052"
  ingress:
    enabled: true
    hosts:
      - host: api.example.local
        paths:
          - path: /
            pathType: Prefix

# Runners configuration
runners:
  nodeSelector: {}

# Wizard configuration
wizard:
  enabled: true
  nodeSelector: {}
  fullnameOverride: "wizard"

# UI configuration
ui:
  nodeSelector: {}
  fullnameOverride: "ui"
  env:
    NEXT_PUBLIC_API_URL: "http://api.example.local"
    NEXTAUTH_URL: "http://console.example.local"
  ingress:
    enabled: true
    hosts:
      - host: console.example.local
        paths:
          - path: /
            pathType: Prefix

# CloudNative PG configuration: https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/values.yaml
cloudnative-pg:
  enabled: true
  fullnameOverride: "cloudnative-pg"

# MinIO configuration: https://github.com/minio/minio/blob/master/helm/minio/values.yaml
minio:
  enabled: true
  fullnameOverride: "minio"
  replicas: 2 # 2 is the minimum
  existingSecret: minio-secret # specify user + password manually to avoid redeployments
  resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 1Gi
  buckets:
    - name: galileo-auto-datasets
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-images
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-models
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-project-runs
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-project-runs-results
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-prompts-datasets
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-prompts-results
      policy: none
      purge: false
      versioning: false
      objectlocking: false
  makePolicyJob:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  makeBucketJob:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  makeUserJob:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  customCommandJob:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  makeServiceAccountJob:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi


# RabbitMQ Operator configuration: https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq-cluster-operator/values.yaml
rabbitmq-cluster-operator:
  resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
  fullnameOverride: "rabbitmq-cluster-operator"
  msgTopologyOperator:
    fullnameOverride: "rabbitmq-messaging-topology-operator"
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi

# Clickhouse configuration: https://github.com/bitnami/charts/blob/main/bitnami/clickhouse/values.yaml
clickhouse:
  enabled: true
  fullnameOverride: "clickhouse"
