nameOverride: ""
fullnameOverride: ""

# API configuration
api:
  ingress:
    enabled: true
    hosts:
      - host: api.local.rungalileo.io
        paths:
          - path: /
            pathType: ImplementationSpecific


# UI configuration
ui:
  ingress:
    enabled: true
    hosts:
      - host: console.local.rungalileo.io
        paths:
          - path: /
            pathType: ImplementationSpecific

# MinIO configuration: https://github.com/minio/minio/blob/master/helm/minio/values.yaml
minio:
  replicas: 2 # 2 is the minimum
  resources:
  requests:
    memory: 1Gi
  buckets:
    - name: galileo-auto-datasets
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-images
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-models
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-project-runs
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-project-runs-results
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-prompts-datasets
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-prompts-results
      policy: none
      purge: false
      versioning: false
      objectlocking: false