nameOverride: ""
fullnameOverride: ""

# Cert-Manager configuration: https://artifacthub.io/packages/helm/cert-manager/cert-manager?modal=values&path=installCRDs
cert-manager:
  installCRDs: true

# API configuration
api:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
    hosts:
      - host: api.local.rungalileo.io
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - api.local.rungalileo.io
        secretName: api-tls-secret

# UI configuration
ui:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
    hosts:
      - host: console.local.rungalileo.io
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - console.local.rungalileo.io
        secretName: ui-tls-secret

# MinIO configuration: https://github.com/minio/minio/blob/master/helm/minio/values.yaml
minio:
  replicas: 2 # 2 is the minimum
  existingSecret: minio-secret # specify user + password manually to avoid redeployments
  resources:
    requests:
      memory: 1Gi
  buckets:
    - name: galileo-auto-datasets
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-images
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-models
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-project-runs
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-project-runs-results
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-prompts-datasets
      policy: none
      purge: false
      versioning: false
      objectlocking: false
    - name: galileo-prompts-results
      policy: none
      purge: false
      versioning: false
      objectlocking: false