{{- if not (lookup "v1" "Secret" .Release.Namespace "api-secret") }}
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
type: Opaque
data:
  GALILEO_API_SECRET_KEY: {{ randAlphaNum 128 | b64enc | quote }}
{{- end }}
