apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-deps
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          command:
            - bash
            - "-c"
            - |
              set -ex
              while [ $(pg_isready -h postgres-1.galileo.svc.cluster.local | echo $?) -ne 0 ]; do
                sleep 10;
              done
              while [ $(pg_isready -h postgres-2.galileo.svc.cluster.local | echo $?) -ne 0 ]; do
                sleep 10;
              done
              while [ $(curl -sw '%{http_code}' "http://minio-client.galileo.svc.cluster.local:9000/minio/health/ready" -o /dev/null) -ne 200 ]; do
                sleep 10;
              done
        - name: alembic-migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          args: ["alembic", "upgrade", "head"]
          env:
            - name: GALILEO_APP
              value: api
            - name: GALILEO_POSTGRES_USER
              value: galileo
            - name: GALILEO_CONSOLE_URL
              value: "https://console.local.rungalileo.io"
            - name: GALILEO_HEADLESS_API_SVC_DNS
              value: "api-hs.galileo.svc.cluster.local"
            - name: GALILEO_RUNNERS_SVC_NAME
              value: "runners-hs.galileo.svc.cluster.local"
            - name: GALILEO_RUNNERS_SVC_PORT
              value: "50052"
            - name: GALILEO_API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: GALILEO_API_SECRET_KEY
            - name: GALILEO_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: dbname
            - name: GALILEO_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: username
            - name: GALILEO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: password
            - name: GALILEO_DATABASE_URL_WRITE
              value: "postgresql://$(GALILEO_DATABASE_USER):$(GALILEO_DATABASE_PASSWORD)@postgres-rw.galileo.svc.cluster.local:5432/$(GALILEO_DATABASE_NAME)"
            - name: GALILEO_DATABASE_URL_READ
              value: "postgresql://$(GALILEO_DATABASE_USER):$(GALILEO_DATABASE_PASSWORD)@postgres-rw.galileo.svc.cluster.local:5432/$(GALILEO_DATABASE_NAME)"
            - name: GALILEO_MINIO_ENDPOINT_URL
              value: "http://galileo-minio.galileo.svc.cluster.local:9000"
            - name: GALILEO_MINIO_K8S_SVC_ADDR
              value: "http://galileo-minio.galileo.svc.cluster.local:9000"
            - name: GALILEO_MINIO_FQDN
              value: "galileo-minio.galileo.svc.cluster.local:9000"
            - name: GALILEO_MINIO_REGION
              value: "us-east-1"
            - name: GALILEO_MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: galileo-minio
                  key: rootUser
            - name: GALILEO_MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: galileo-minio
                  key: rootPassword
          # envFrom:
          # - configMapRef:
          #     name: galileo-config
          # - configMapRef:
          #     name: objectstore-config
          # - secretRef:
          #     name: postgres
          # - secretRef:
          #     name: minio
          # - secretRef:
          #     name: api-secret
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: GALILEO_CONSOLE_URL
              value: "https://console.local.rungalileo.io"
            - name: GALILEO_HEADLESS_API_SVC_DNS
              value: "api-hs.galileo.svc.cluster.local"
            - name: GALILEO_RUNNERS_SVC_NAME
              value: "runners-hs.galileo.svc.cluster.local"
            - name: GALILEO_RUNNERS_SVC_PORT
              value: "50052"
            - name: GALILEO_API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: GALILEO_API_SECRET_KEY
            - name: GALILEO_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: dbname
            - name: GALILEO_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: username
            - name: GALILEO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: password
            - name: GALILEO_DATABASE_URL_WRITE
              value: "postgresql://$(GALILEO_DATABASE_USER):$(GALILEO_DATABASE_PASSWORD)@postgres-rw.galileo.svc.cluster.local:5432/$(GALILEO_DATABASE_NAME)"
            - name: GALILEO_DATABASE_URL_READ
              value: "postgresql://$(GALILEO_DATABASE_USER):$(GALILEO_DATABASE_PASSWORD)@postgres-rw.galileo.svc.cluster.local:5432/$(GALILEO_DATABASE_NAME)"
            - name: GALILEO_MINIO_ENDPOINT_URL
              value: "http://galileo-minio.galileo.svc.cluster.local:9000"
            - name: GALILEO_MINIO_K8S_SVC_ADDR
              value: "http://galileo-minio.galileo.svc.cluster.local:9000"
            - name: GALILEO_MINIO_FQDN
              value: "galileo-minio.galileo.svc.cluster.local:9000"
            - name: GALILEO_MINIO_REGION
              value: "us-east-1"
            - name: GALILEO_MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: galileo-minio
                  key: rootUser
            - name: GALILEO_MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: galileo-minio
                  key: rootPassword
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
