apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-deps
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command:
            - "bash"
            - "-c"
            - |
              set -ex
              echo "Checking readiness of primary Postgres DB..."
              while ! pg_isready -h {{.Values.postgres.write.host}}; do
                echo "Postgres DB is not ready yet, sleeping for 10 seconds..."
                sleep 10
              done
              echo "Postgres DB is ready."

              echo "Checking readiness of Minio client..."
              while [ $(curl -sw '%{http_code}' "http://minio-client.{{ .Release.Namespace }}.svc.cluster.local:9000/minio/health/ready" -o /dev/null) -ne 200 ]; do
                echo "Minio client is not ready yet, sleeping for 10 seconds..."
                sleep 10
              done
              echo "Minio client is ready."
        - name: alembic-migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command:
            - "bash"
            - "-c"
            - "poetry run alembic upgrade head"
          env:
            - name: GALILEO_APP
              value: api
            - name: GALILEO_API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: GALILEO_API_SECRET_KEY
            - name: GALILEO_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: dbname
            - name: GALILEO_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: username
            - name: GALILEO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: password
            - name: GALILEO_DATABASE_URL_WRITE
              value: "postgresql://$(GALILEO_DATABASE_USER):$(GALILEO_DATABASE_PASSWORD)@{{.Values.postgres.write.host}}:{{.Values.postgres.write.port}}/$(GALILEO_DATABASE_NAME)"
            - name: GALILEO_DATABASE_URL_READ
              value: "postgresql://$(GALILEO_DATABASE_USER):$(GALILEO_DATABASE_PASSWORD)@{{.Values.postgres.read.host}}:{{.Values.postgres.read.port}}/$(GALILEO_DATABASE_NAME)"
            - name: GALILEO_MINIO_REGION
              value: {{ .Values.cloud.region }}
            - name: GALILEO_MINIO_FQDN
              value: {{ if eq .Values.cloud.vendor "s3" }}"s3.amazonaws.com"{{ else if eq .Values.cloud.vendor "gs" }}"storage.googleapis.com"{{ else }}{{ .Values.cloud.endpointURL }}{{ end }}
            - name: GALILEO_MINIO_ENDPOINT_URL
              value: "http://{{ .Values.cloud.endpointURL }}"
            - name: GALILEO_MINIO_K8S_SVC_ADDR
              value: "http://{{ .Values.cloud.endpointURL }}"
            - name: GALILEO_MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: rootUser
            - name: GALILEO_MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: rootPassword
            {{- with .Values.env }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # Initialize the Celery service with `bash -c` to ensure that the command is executed in a shell.
          # This is necessary to ensure that the process receives the control signals sent by Kubernetes for
          # graceful termination.
          command:
            - "bash"
            - "-c"
            - "poetry run opentelemetry-instrument gunicorn api.main:api -c api/gunicorn_config.py"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: GALILEO_RABBITMQ_HOST
              value: "rabbitmq-cluster.{{ .Release.Namespace }}.svc.cluster.local"
            - name: GALILEO_RABBITMQ_PORT
              value: "5672"
            - name: GALILEO_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-cluster-default-user
                  key: username
            - name: GALILEO_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-cluster-default-user
                  key: password
            - name: GALILEO_API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: GALILEO_API_SECRET_KEY
            - name: GALILEO_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: dbname
            - name: GALILEO_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: username
            - name: GALILEO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: password
            - name: GALILEO_DATABASE_URL_WRITE
              value: "postgresql://$(GALILEO_DATABASE_USER):$(GALILEO_DATABASE_PASSWORD)@{{.Values.postgres.write.host}}:{{.Values.postgres.write.port}}/$(GALILEO_DATABASE_NAME)"
            - name: GALILEO_DATABASE_URL_READ
              value: "postgresql://$(GALILEO_DATABASE_USER):$(GALILEO_DATABASE_PASSWORD)@{{.Values.postgres.read.host}}:{{.Values.postgres.read.port}}/$(GALILEO_DATABASE_NAME)"
            - name: CLOUD_VENDOR_OBJECTSTORE
              value: {{ .Values.cloud.vendor }}
            - name: GALILEO_MINIO_REGION
              value: {{ .Values.cloud.region }}
            - name: GALILEO_MINIO_FQDN
              value: {{ if eq .Values.cloud.vendor "s3" }}"s3.amazonaws.com"{{ else if eq .Values.cloud.vendor "gs" }}"storage.googleapis.com"{{ else }}{{ .Values.cloud.endpointURL }}{{ end }}
            - name: GALILEO_MINIO_ENDPOINT_URL
              value: "http://{{ .Values.cloud.endpointURL }}"
            - name: GALILEO_MINIO_K8S_SVC_ADDR
              value: "http://{{ .Values.cloud.endpointURL }}"
            - name: GALILEO_MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: rootUser
            - name: GALILEO_MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: rootPassword
            {{- with .Values.env }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            successThreshold: 1
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            successThreshold: 1
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            periodSeconds: 10
            failureThreshold: 30
            httpGet:
              path: /healthcheck
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
