{{- if not (lookup "v1" "Secret" .Release.Namespace "minio-secret") }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  rootUser: {{ randAlphaNum 32 | b64enc | quote }}
  rootPassword: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}