{{- if not (lookup "v1" "Secret" .Release.Namespace "ui-secret") }}
apiVersion: v1
kind: Secret
metadata:
  name: ui-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
type: Opaque
data:
  GALILEO_UI_SECRET_KEY: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
